import type { OutletSignal } from "@barops/shared-types";

export const demoOutletSignals: OutletSignal[] = [
  {
    outletId: "a6f40d49-6bae-4f13-a20b-9b1375d8e101",
    outletCode: "BLR-IND-001",
    outletName: "MG Road Premium Spirits",
    city: "Bengaluru",
    state: "Karnataka",
    source: "POS",
    date: "2026-04-14",
    stockVariancePercent: 2.9,
    ownBaselineDeviationPercent: 42,
    peerDeviationPercent: 36,
    lateUploads7d: 5,
    missingUploadToday: true,
    correctionCount7d: 4,
    correctionCount30d: 12,
    correctionChainLength: 3,
    premiumMixPercent: 51,
    premiumMixBaselinePercent: 29,
    topBrandDropPercent: 38,
    topBrandUnitsToday: 48,
    topBrandUnitsBaseline: 80,
    riskScore7dAverage: 77,
    unresolvedAnomalyCount: 7,
    highRiskDaysStreak: 5
  },
  {
    outletId: "b3ed0a98-f6f8-4fe8-aea6-c407f90f43d0",
    outletCode: "PUN-MH-014",
    outletName: "Baner Cellars",
    city: "Pune",
    state: "Maharashtra",
    source: "EXCEL",
    date: "2026-04-14",
    stockVariancePercent: 3.8,
    ownBaselineDeviationPercent: 24,
    peerDeviationPercent: 17,
    lateUploads7d: 2,
    missingUploadToday: false,
    correctionCount7d: 2,
    correctionCount30d: 5,
    correctionChainLength: 1,
    premiumMixPercent: 33,
    premiumMixBaselinePercent: 23,
    topBrandDropPercent: 22,
    topBrandUnitsToday: 78,
    topBrandUnitsBaseline: 100,
    riskScore7dAverage: 52,
    unresolvedAnomalyCount: 3,
    highRiskDaysStreak: 2
  },
  {
    outletId: "0e2f8f31-3968-4ea2-84aa-7bbfdb2152a8",
    outletCode: "HYD-TG-022",
    outletName: "Jubilee Hills Reserve",
    city: "Hyderabad",
    state: "Telangana",
    source: "MANUAL_UPLOAD",
    date: "2026-04-14",
    stockVariancePercent: 1.1,
    ownBaselineDeviationPercent: 8,
    peerDeviationPercent: 9,
    lateUploads7d: 0,
    missingUploadToday: false,
    correctionCount7d: 0,
    correctionCount30d: 1,
    correctionChainLength: 0,
    premiumMixPercent: 21,
    premiumMixBaselinePercent: 20,
    topBrandDropPercent: 6,
    topBrandUnitsToday: 112,
    topBrandUnitsBaseline: 118,
    riskScore7dAverage: 18,
    unresolvedAnomalyCount: 1,
    highRiskDaysStreak: 0
  }
];
