import type { OutletAttention } from "@barops/shared-types";

export function renderDailyAttentionMarkdown(
  runDate: string,
  outlets: OutletAttention[]
): string {
  const heading = `# Daily Attention Report (${runDate})`;
  const intro =
    "Generated by BarOps Authority demo. Prioritize these outlets for central-office review.";

  const rows = outlets
    .sort((a, b) => b.riskScore - a.riskScore)
    .map(
      (outlet, index) =>
        `${index + 1}. **${outlet.outletName}** (${outlet.city}, ${outlet.state}) - ` +
        `Risk ${outlet.riskScore} - ${outlet.reasons.join("; ")}`
    );

  return [heading, "", intro, "", ...rows].join("\n");
}
